version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: |
      /bin/sh -c "while sleep 1000; do :; done"
    environment:
      DB_HOST: db
      DB_NAME: devdb
      DB_USER: devuser
      DB_PASS: devpass
    depends_on:
      - db

  db:
    image: postgres:15.0-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass

volumes:
  dev-db-data:
